### ISSUE TITLE
[question] different between is.Domain and is.DNSName

### ISSUE THREAD

**Issue by bokunodev** [jellydator/validation#4]
whats the different between `is.Domain` and  `is.DNSName`?

**Comment by swithek** [comment]
The regexp patterns are different. There's a comment explaining why Domain's pattern is like this [here](https://github.com/jellydator/validation/blob/master/is/rules.go#L253).

Also, most of these helper functions are using govalidator under the hood. Here's the [DNSName](https://github.com/asaskevich/govalidator/blob/f21760c49a8d/validator.go#L675)'s implementation.
